name: Build and Deploy Angular App

on:
  push:
    branches: [ master ]  # o "main" si usas esa rama

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Build de la app
        run: npm run build --prod  # --prod para producción

      - name: Deploy a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Asegúrate de que sea la rama correcta
          folder: dist/deployment  # Cambia esto por el nombre de tu app en el dist
          token: ${{ secrets.GH_TOKEN }}  # El token secreto para permitir el deploy
